version: '3.8'
services: 
    db:
      image: mongo:5.0.6
      ports:
        - "27017:27017"
      volumes:
        - db:/testdb
    web:
      depends_on:
        - db
      build: .
      ports:
        - "4567:4567"
volumes:
  db: