version: '3.8'
services: 
    db:
      image: mongo:5.0.6
      ports:
        - "27017:27017"
    web:
      environment:
        - DEBUG=True
      build: .
      volumes:
        - .:/code
      ports:
        - "4567:4567"
      depends_on:
        - db
volumes:
  db: